export default interface RoleInfo {
  id: number;
  userManorId: number;
  userId: number;
  goodsId: number;
  orderNo: string;
  type: string;
  seedsType: string;
  name: string;
  level: string;
  growthPeriodType: string;
  growthPeriodName: string;
  outputValue: number;
  harvestIntegral: number;
  growthValue: number;
  growthPeriod: string;
  multipleOutput: string;
  speedOrSlowGrowthOutput: string;
  speedOrSlowTimeOutput: string;
  imgUrl: string;
  useNum: number;
  usedNum: number;
  residueNum: number;
  experience: number;
  status: string;
  validityPeriod: string;
  expireDate: string;
  energyValue: string;
  movementSpeed: string;
  powerValue: string;
  residueEnergyValue: string;
  figureX: number;
  figureY: number;
  createDate: string;
  updateDate: string;
  remarks: string;
  arriveDate:string;
  seedingCountdown:string;
}

